# Generated by Django 5.0.7 on 2024-07-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_course_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='A school_year value is valid between 1 and 10',
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(('school_year__gte', 1), ('school_year__lt', 4)), name='A school_year value is valid between 1 and 4'),
        ),
    ]
